import {Component, EventEmitter, OnInit, Output} from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
    <input [value]="title"
           (keyup.enter)="changeTitle(inputElement.value)"
           #inputElement>
    <button (click)="changeTitle(inputElement.value)" class="btn">
      Save
    </button>
  `,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {
  @Output() submit: EventEmitter<string> = new EventEmitter();
  public title = 'my title';

  constructor() {
    console.log('in constructor');
    console.log(this.title);
  }

  changeTitle(newTitle: string): void {
    this.submit.emit(newTitle);
  }

  ngOnInit() {
/*    setTimeout(() => {
      this.title = 'This is not the title you are looking for';
    }, 3000);*/
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }


}
